micronaut:
  application:
    name: ecochargerent
  security:
    enable: false
  data:
    mongodb:
      driver-type: reactive
      create-collections: true
flyway:
  datasources:
    default:
      enabled: true

mongodb:
  uri:

jackson:
  serialization:
    writeEnumsUsingToString: true
    writeDatesAsTimestamps: false
  deserialization:
    readEnumsUsingToString: true
    failOnUnknownProperties: false
    failOnInvalidSubtype: false
